### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by gotmax23** [Rogdham/pyzstd#13]
The package currently fails to build with Python 3.13 due to changes in the Python C API:

```
  src/bin_ext/macro_functions.h: In function ‘set_c_parameters’:
  src/bin_ext/macro_functions.h:17:27: error: implicit declaration of function ‘_PyLong_AsInt’; did you mean ‘PyLong_AsInt’? [-Wimplicit-function-declaration]
     17 |         const int level = _PyLong_AsInt(level_or_option);
        |                           ^~~~~~~~~~~~~
        |                           PyLong_AsInt
```

**Comment by Rogdham** [comment]
Thank you for the heads up about the breaking change in the next version of Python!
