### PR TITLE
Replace _PyLong_AsInt() with PyLong_AsInt() for Python 3.13+

### LINKED ISSUE #13: Add support for Python 3.13
The package currently fails to build with Python 3.13 due to changes in the Python C API:

```
  src/bin_ext/macro_functions.h: In function ‘set_c_parameters’:
  src/bin_ext/macro_functions.h:17:27: error: implicit declaration of function ‘_PyLong_AsInt’; did you mean ‘PyLong_AsInt’? [-Wimplicit-function-declaration]
     17 |         const int level = _PyLong_AsInt(level_or_option);
        |                           ^~~~~~~~~~~~~
        |                           PyLong_AsInt
```

### PR DESCRIPTION
**Pull request by mikelolasagasti**
The new public function `PyLong_AsInt()` has been introduced as part of https://github.com/python/cpython/issues/108444, which renames the internal `_PyLong_AsInt()` to `PyLong_AsInt()`. This change updates the code to use the new public API while maintaining compatibility with Python versions earlier than 3.13.

Fixes #13

### CODE REVIEW

**Comment by Rogdham** [comment]
Thank you for the PR!

I have changed the version check to replicate the one in https://github.com/python/pythoncapi-compat/blob/18d1df75c72a4ac38fc0a934c13ab6de081a19d2/pythoncapi_compat.h#L887
